# 1. Objects
obj-y += kernel/ksu.o
obj-y += allowlist.o
obj-y += apk_sign.o
obj-y += app_profile.o
obj-y += extras.o
obj-y += feature.o
obj-y += file_wrapper.o
obj-y += kernel_compat.o
obj-y += kernel_umount.o
obj-y += ksud.o
obj-y += lsm_hooks.o
obj-y += seccomp_cache.o
obj-y += setuid_hook.o
obj-y += su_mount_ns.o
obj-y += sucompat.o
obj-y += supercalls.o
obj-y += syscall_hook_manager.o
obj-y += throne_tracker.o
obj-y += tiny_sulog.o
obj-y += util.o
obj-y += selinux/rules.o
obj-y += selinux/selinux.o
obj-y += selinux/sepolicy.o

# 2. Fix Includes (Relative to this folder)
ccflags-y += -I$(srctree)/security/selinux/include
ccflags-y += -I$(srctree)/$(src)/kernel
ccflags-y += -I$(srctree)/$(src)/selinux

# 3. Enable KSU Manual Hook Flags
ccflags-y += -DCONFIG_KSU_NEXT_MANUAL_HOOK

# 4. THE V2 SIGNATURE (Handshake for Genuine status)
# Hardcode the hash here to avoid shell quoting issues in the .yml
KSU_HASH := 79e590113c4c4c0c222978e413a5faa801666957b1212a328e46c00c69821bf7
ccflags-y += -DKSU_NEXT_EXPECTED_SIZE=0x3e6
ccflags-y += -DKSU_NEXT_EXPECTED_HASH=\"$(KSU_HASH)\"

# Silence Clang warnings
ccflags-y += -Wno-strict-prototypes -Wno-implicit-function-declaration -Wno-declaration-after-statement
